project:
  type: website
  output-dir: docs

website:
  title: "quarto5"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: labs.qmd
        text: Labs
      - href: project.qmd
        text: Project
      - href: presentation.qmd
        text: Presentation
      - href: about.qmd
        text: About
        
format:
  html:
    theme: quartz
    css: styles.css
    toc: true

editor: visual

